### ISSUE TITLE
Installation Error: CUDA version mismatches

### ISSUE THREAD

**Issue by Minbz** [hbb1/2d-gaussian-splatting#78]
Hi, I encountered the following error message while trying to build the Conda environment:
`conda env create --file environment.yml`

I'm using wsl2 on Windows and tried CUDA toolkit versions 12.1 and 12.5, but both resulted in the same error messages below.

`× python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      running bdist_wheel
      /home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/c/Users/min_w/Desktop/2d-gaussian-splatting/submodules/simple-knn/setup.py", line 21, in <module>
          setup(
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/mbz1325038/miniconda3/envs/surfel_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.

      [end of output]`

I wonder which CUDA version is compatible. Alternatively, could there be any other cause for this problem?
Thank you!

**Comment by hbb1** [comment]
It seems like you installed a pytorch version with cuda mismatch your actual cuda version.

**Comment by hbb1** [comment]
that is said, if you cuda toolkit is 12.1 then you should install pytorch+cu121. You can find it out here https://pytorch.org/get-started/previous-versions/

**Comment by Minbz** [comment]
> that is said, if your cuda toolkit is 12.1 then you should install pytorch+cu121. You can find it out here https://pytorch.org/get-started/previous-versions/

Thank you! The error was resolved by reinstalling the matching CUDA toolkit as you suggested.
